Add error checking after site-install and runserver.

diff --git a/scripts/setup-before-tests b/scripts/setup-before-tests
--- a/scripts/setup-before-tests
+++ b/scripts/setup-before-tests
@@ -7,11 +7,8 @@
 #
 # Usage:
 #
-#    In a project that has 'require pantheon-systems/travis-scripts'
-#    in its composer.json:
-#
 #    compser install
-#    ./bin/setup-before-tests
+#    ./travis/setup-before-tests.sh
 #    ./bin/behat
 #
 
@@ -40,7 +37,17 @@ cp $PROJECT_BASE_DIR/htdocs/sites/default/default.settings.php $PROJECT_BASE_DIR
 # Use Drush to install Drupal and spin up PHP's built-in webserver
 cd $PROJECT_BASE_DIR/htdocs
 drush site-install -y standard --site-name="$SITE_NAME Travis Test Site" --db-url=mysql://root@localhost/drupal --account-name=admin --account-pass=admin
+if [ $? != 0 ]
+then
+  echo "Could not install Drupal" >&2
+  exit 1
+fi
 drush runserver --server=builtin 8088 --strict=0 </dev/null &>$HOME/server.log &
+if [ $? != 0 ]
+then
+  echo "Could nt start php built-in webserver" >&2
+  exit 1
+fi
 cd $PROJECT_BASE_DIR
 
 # Wait for the webserver to spin up; stop when we find someone listening on the right port.
